"""Dataclasses corresponding to the content defined in json_resume.SimpleSchema. This file was generated by an agent."""

import json
import re

from dataclasses import dataclass, field
from datetime import date as CalendarDate  # noqa: N812
from typing import TYPE_CHECKING, Annotated, Any

import yaml

from pydantic import BeforeValidator, TypeAdapter

if TYPE_CHECKING:
    from pathlib import Path


# ----------------------------------------------------------------------
# JSON Resume does not distinguish between a uri and a string at the type level;
# the alias exists to preserve the distinction made within the schema file.
type Uri = str


# ----------------------------------------------------------------------
@dataclass(frozen=True)
class ResumeDate:
    """A JSON Resume date; the month and the day that follows it are optional."""

    year: int
    month: int | None = None
    day: int | None = None


# ----------------------------------------------------------------------
def _ToResumeDate(value: Any) -> Any:  # noqa: ANN401
    """Convert the forms that a date may be written in into a `ResumeDate`.

    YAML resolves a complete date into a `date` and a year into an `int`, so the value provided here
    is not always the string that JSON Resume defines.
    """

    if isinstance(value, CalendarDate):
        return ResumeDate(value.year, value.month, value.day)

    if isinstance(value, int):
        value = str(value)

    if isinstance(value, str):
        match = _DATE_REGEX.match(value)

        if match is None:
            msg = f"'{value}' is not a valid date; expected 'YYYY', 'YYYY-MM', or 'YYYY-MM-DD'."
            raise ValueError(msg)

        year, month, day = (int(item) if item is not None else None for item in match.groups())

        # The pattern recognizes the shape of a date rather than the days that a month actually has,
        # so the value is constructed to reject those that a calendar does not contain.
        CalendarDate(year, month or 1, day or 1)  # ty: ignore[invalid-argument-type]

        return ResumeDate(year, month, day)  # ty: ignore[invalid-argument-type]

    return value


# A date is complete, or it omits the day, or it omits the month as well.
_DATE_REGEX = re.compile(r"^(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?$")

Date = Annotated[ResumeDate, BeforeValidator(_ToResumeDate)]


# ----------------------------------------------------------------------
# |
# |  <basics>
# |
# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Location:
    """<basics.location>"""  # noqa: D400, D415

    address: str
    postalCode: str  # noqa: N815
    city: str
    countryCode: str | None = None  # ISO-3166-1 ALPHA-2  # noqa: N815
    region: str | None = None  # state or province


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Profile:
    """<basics.profiles>"""  # noqa: D400, D415

    network: str
    username: str
    url: Uri


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Basics:
    """<basics>"""  # noqa: D400, D415

    name: str
    label: str | None = None
    image: Uri | None = None
    email: str | None = None
    phone: str | None = None
    url: Uri | None = None
    summary: str | None = None

    location: Location | None = None
    profiles: list[Profile] = field(default_factory=list)


# ----------------------------------------------------------------------
# |
# |  Sections
# |
# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Work:
    """<work>"""  # noqa: D400, D415

    name: str  # the company
    location: str | None = None  # e.g. Menlo Park, CA
    description: str | None = None  # e.g. Social Media Company
    position: str
    url: Uri | None = None
    startDate: Date  # noqa: N815
    endDate: Date | None = None  # noqa: N815
    summary: str
    highlights: list[str] = field(default_factory=list)


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Volunteer:
    """<volunteer>"""  # noqa: D400, D415

    organization: str
    position: str
    url: Uri | None = None
    startDate: Date  # noqa: N815
    endDate: Date | None = None  # noqa: N815
    summary: str
    highlights: list[str] = field(default_factory=list)


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Education:
    """<education>"""  # noqa: D400, D415

    institution: str
    url: Uri | None = None
    area: str
    studyType: str  # noqa: N815
    startDate: Date | None = None  # noqa: N815
    endDate: Date | None = None  # noqa: N815
    score: str | None = None  # grade point average
    courses: list[str] = field(default_factory=list)


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Award:
    """<awards>"""  # noqa: D400, D415

    title: str
    date: Date
    awarder: str
    summary: str


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Certificate:
    """<certificates>"""  # noqa: D400, D415

    name: str
    date: Date | None = None
    url: Uri | None = None
    issuer: str


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Publication:
    """<publications>"""  # noqa: D400, D415

    name: str
    publisher: str
    releaseDate: Date  # noqa: N815
    url: Uri | None = None
    summary: str


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Skill:
    """<skills>"""  # noqa: D400, D415

    name: str
    level: str | None = None  # e.g. Master
    keywords: list[str] = field(default_factory=list)


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Language:
    """<languages>"""  # noqa: D400, D415

    language: str
    fluency: str


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Interest:
    """<interests>"""  # noqa: D400, D415

    name: str
    keywords: list[str] = field(default_factory=list)


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Reference:
    """<references>"""  # noqa: D400, D415

    name: str
    reference: str | None = None


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Project:
    """<projects>"""  # noqa: D400, D415

    name: str
    description: str
    highlights: list[str] = field(default_factory=list)
    keywords: list[str] = field(default_factory=list)
    startDate: Date | None = None  # noqa: N815
    endDate: Date | None = None  # noqa: N815
    url: Uri | None = None
    roles: list[str] = field(default_factory=list)
    entity: str | None = None  # e.g. greenpeace
    type: str | None = None  # e.g. volunteering, presentation, talk, application, conference


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Meta:
    """<meta>"""  # noqa: D400, D415

    canonical: Uri | None = None
    version: str | None = None  # semver, e.g. v1.0.0
    lastModified: str | None = None  # ISO 8601, e.g. 2014-06-29T09:00:00  # noqa: N815


# ----------------------------------------------------------------------
# |
# |  <resume_data>
# |
# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class ResumeData:
    """<resume_data>"""  # noqa: D400, D415

    basics: Basics
    work: list[Work] = field(default_factory=list)
    volunteer: list[Volunteer] = field(default_factory=list)
    education: list[Education] = field(default_factory=list)
    awards: list[Award] = field(default_factory=list)
    certificates: list[Certificate] = field(default_factory=list)
    publications: list[Publication] = field(default_factory=list)
    skills: list[Skill] = field(default_factory=list)
    languages: list[Language] = field(default_factory=list)
    interests: list[Interest] = field(default_factory=list)
    references: list[Reference] = field(default_factory=list)
    projects: list[Project] = field(default_factory=list)
    meta: Meta | None = None

    # ----------------------------------------------------------------------
    @staticmethod
    def FromFile(filename: Path) -> ResumeData:
        """Create an instance of this class based on the contents of the specified file."""

        if filename.suffix.lower() in (".yaml", ".yml"):
            read_func = yaml.safe_load
        elif filename.suffix.lower() == ".json":
            read_func = json.load
        else:
            msg = f"'{filename}' is not a supported file type."
            raise ValueError(msg)

        with filename.open(encoding="utf-8") as f:
            content = read_func(f)

        return _resume_data_type_adapter.validate_python(content)


# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
_resume_data_type_adapter = TypeAdapter(ResumeData)
