"""Dataclasses corresponding to the content defined in json_resume.SimpleSchema. This file was generated by an agent."""

import json

from dataclasses import dataclass, field
from datetime import date as Date  # noqa: N812, TC003
from enum import StrEnum
from typing import TYPE_CHECKING

import yaml

from pydantic import TypeAdapter

if TYPE_CHECKING:
    from pathlib import Path


# ----------------------------------------------------------------------
# JSON Resume does not distinguish between a uri and a string at the type level;
# the alias exists to preserve the distinction made within the schema file.
type Uri = str


# ----------------------------------------------------------------------
class SkillLevel(StrEnum):
    """<skills.level>"""  # noqa: D400, D415

    Beginner = "Beginner"
    Intermediate = "Intermediate"
    Advanced = "Advanced"
    Master = "Master"


# ----------------------------------------------------------------------
# |
# |  <basics>
# |
# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Location:
    """<basics.location>"""  # noqa: D400, D415

    address: str
    city: str
    postalCode: str  # noqa: N815
    countryCode: str | None = None  # noqa: N815
    region: str | None = None  # state


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Profile:
    """<basics.profiles>"""  # noqa: D400, D415

    network: str
    username: str
    url: Uri


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Basics:
    """<basics>"""  # noqa: D400, D415

    name: str
    label: str | None = None
    picture: Uri | None = None
    email: str | None = None
    phone: str | None = None
    website: Uri | None = None
    summary: str | None = None

    location: Location | None = None
    profiles: list[Profile] = field(default_factory=list)


# ----------------------------------------------------------------------
# |
# |  Sections
# |
# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Work:
    """<work>"""  # noqa: D400, D415

    company: str
    position: str
    website: Uri | None = None
    startDate: Date  # noqa: N815
    endDate: Date | None = None  # noqa: N815
    summary: str
    highlights: list[str] = field(default_factory=list)


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Volunteer:
    """<volunteer>"""  # noqa: D400, D415

    organization: str
    website: Uri | None = None
    position: str
    startDate: Date  # noqa: N815
    endDate: Date | None = None  # noqa: N815
    summary: str
    highlights: list[str] = field(default_factory=list)


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Education:
    """<education>"""  # noqa: D400, D415

    institution: str
    area: str
    studyType: str  # noqa: N815
    startDate: Date | None = None  # noqa: N815
    endDate: Date | None = None  # noqa: N815
    gpa: str | None = None
    courses: list[str] = field(default_factory=list)


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Award:
    """<awards>"""  # noqa: D400, D415

    title: str
    date: Date
    awarder: str
    summary: str


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Publication:
    """<publications>"""  # noqa: D400, D415

    name: str
    publisher: str
    releaseDate: Date  # noqa: N815
    website: Uri | None = None
    summary: str


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Skill:
    """<skills>"""  # noqa: D400, D415

    name: str
    level: SkillLevel | None = None
    keywords: list[str] = field(default_factory=list)


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Language:
    """<languages>"""  # noqa: D400, D415

    language: str
    fluency: str


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Interest:
    """<interests>"""  # noqa: D400, D415

    name: str
    keywords: list[str] = field(default_factory=list)


# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class Reference:
    """<references>"""  # noqa: D400, D415

    name: str
    reference: str | None = None


# ----------------------------------------------------------------------
# |
# |  <resume_data>
# |
# ----------------------------------------------------------------------
@dataclass(kw_only=True)
class ResumeData:
    """<resume_data>"""  # noqa: D400, D415

    basics: Basics
    work: list[Work] = field(default_factory=list)
    volunteer: list[Volunteer] = field(default_factory=list)
    education: list[Education] = field(default_factory=list)
    awards: list[Award] = field(default_factory=list)
    publications: list[Publication] = field(default_factory=list)
    skills: list[Skill] = field(default_factory=list)
    languages: list[Language] = field(default_factory=list)
    interests: list[Interest] = field(default_factory=list)
    references: list[Reference] = field(default_factory=list)
    meta: object = None

    # ----------------------------------------------------------------------
    @staticmethod
    def FromFile(filename: Path) -> ResumeData:
        """Create an instance of this class based on the contents of the specified file."""

        if filename.suffix.lower() in (".yaml", ".yml"):
            read_func = yaml.safe_load
        elif filename.suffix.lower() == ".json":
            read_func = json.load
        else:
            msg = f"'{filename}' is not a supported file type."
            raise ValueError(msg)

        with filename.open(encoding="utf-8") as f:
            content = read_func(f)

        return _resume_data_type_adapter.validate_python(content)


# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
_resume_data_type_adapter = TypeAdapter(ResumeData)
